spring:
  application:
    name: kampilan-fc
  profiles:
    default: dev

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/kampilanfc?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        jdbc.time_zone: UTC

flyway:
  enabled: true
  locations: classpath:/db/migration
  baseline-on-migrate: true

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: never
    include-binding-errors: never

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
